[package]
name = "sezkp-ffts"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "SEZKP finite fields + naive DFT bootstrap"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "ntt"
harness = false

